#!/bin/bash

if [ $UID = 0 ]
then SUDO=
else SUDO="sudo -E"
fi

if [ ! -e $(dirname "$0")/.workdir.conf ]
then
    echo "$(dirname $0)/.workdir.conf does not exist."
    echo "Please run the GoboALFS script before launching this script."
    exit 1
fi

source $(dirname "$0")/.workdir.conf
BUILDDIR=$WORKDIR/RootFS

umount_sys=
umount_proc=
umount_dev=
mountpoint -q "$BUILDDIR/sys"  || { $SUDO mount -o bind /sys "$BUILDDIR/sys"; umount_sys=yes; }
mountpoint -q "$BUILDDIR/proc" || { $SUDO mount -o bind /proc "$BUILDDIR/proc"; umount_proc=yes; }
mountpoint -q "$BUILDDIR/dev"  || { $SUDO mount -o bind /dev "$BUILDDIR/dev"; umount_dev=yes; }

export PATH=/bin:/sbin:$PATH
export SUDO_OK=1
export SUDO_PS1="[\u@gobolinux-chroot \W]\$ "
unset LC_ALL
unset LANG
unset LANGUAGE

$SUDO chroot "$BUILDDIR" /bin/bash


[ "$umount_dev" = "yes" ]  && $SUDO umount "$BUILDDIR/dev"
[ "$umount_proc" = "yes" ] && $SUDO umount "$BUILDDIR/proc"
[ "$umount_sys" = "yes" ]  && $SUDO umount "$BUILDDIR/sys"
