#!/bin/bash

WORKDIR=$(readlink -f $(dirname "$0")/../WorkDirectory)

# VGA options are:
# -vga [std|cirrus|vmware|qxl|xenfb|none

sudo qemu-system-i386 \
    --enable-kvm \
    -usb \
    -vga qxl \
    -net nic,macaddr=E0:06:E6:CE:FF:FF,model=virtio -net tap,ifname=tap0,script=no \
    -hda /Data/VMs/gobolinux-015-i686.img \
    -cdrom "$WORKDIR/ISO/Output/GoboLinux-NoVersion.iso" \
    -boot d
